#!/bin/bash


user_path="/nfs/sgoinfre/goinfre/Perso/$USER"

du -sh $user_path | awk '{printf ("\033[31mBefore Cleaning: %s\033[0m\n\n", $1)}'

sleep 1

awk 'BEGIN {printf ("\033[33mLoading...\033[0m\n\n")}'

rm -f ${user_path}/THE\ OS/Snapshots/*

sleep 2

du -sh $user_path | awk '{printf ("\033[32mAfter Cleaning: %s\033[0m\n\n", $1)}'

#sleep 3

#slock
