#!/bin/bash

RED='\033[31m'
END='\033[0m'
YELLOW='\033[33m'
localpath="/nfs/homes/ysbai-jo/"
l_path="Downloads"
v_path="SCP_DIR/*"
vmpath="/home/os/"
option=""
ip="10.13.13.13"
flag=false



function is_valid_ip() {
    local ip=$1
    local valid_ip_regex='^([0-9]{1,3}\.){3}[0-9]{1,3}$'
    if [[ $ip =~ $valid_ip_regex ]]; then
        IFS='.' read -r -a octets <<< "$ip"
        for octet in "${octets[@]}"; do
            if (( octet < 0 || octet > 255 )); then
                return 1
            fi
        done
        return 0
    else
        return 1
    fi
}


while getopts ":v:l:i:r:" opt; do
	case ${opt} in
	v)
		v_path="$OPTARG"
		;;
	l | r)
		option="-r"
		l_path="$OPTARG"
		if [[ "$l_path" == /* ]];
		then
			localpath="$l_path"
		elif [[ $l_path == .* ]];
		then
			localpath=$(realpath "$l_path")
		else
			localpath+="$l_path"
		fi
		
		if ! [ -d $localpath ];
		then
			echo -e "${YELLOW}path \"$localpath\" not found !${END}"
			exit 3;
		fi
		;;
	i)
		flag=true
		ip="$OPTARG"
		;;
	\?)
		echo -e "${RED}invalid option \"-$OPTARG\"${END}"
		exit 1
		;;
	:)
		if [ $OPTARG == "r" ];
		then
			echo -e "scp2: ${YELLOW}usage: -r [localpath]${END}"
		elif [ $OPTARG == "i" ];
		then
			echo -e "scp2: usage: -i [__ip_address]"
		else
			echo -e "scp2: ${YELLOW}option \"-$OPTARG\" requires an argument !${END}"
		fi
		exit 2
		;;
	esac
done

shift $((OPTIND - 1))

vmpath+="$v_path"

if [ "$flag" == "true" ];
then
	if ! is_valid_ip "$ip";
	then
		echo -e "scp2: ${RED}invalid ip address \"$ip\"${END}"
		exit 10
	fi
fi

echo "option $option"
echo "ip $ip"
echo "vmpath $vmpath"
echo "local path $localpath"


# scp ${option} os@${ip}:${vmpath} ${localpath}
